# Generated by Django 6.1.1 on 2026-09-30 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('motif', models.TextField(blank=True, verbose_name='motif de consultation')),
                ('diagnostic', models.TextField(blank=True, verbose_name='diagnostic')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('constantes', models.JSONField(blank=True, help_text='Tension, pouls, température, poids, taille, IMC', null=True, verbose_name='constantes')),
                ('prescription', models.TextField(blank=True, verbose_name='prescription')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('cloturee', 'Clôturée')], default='ouverte', max_length=20, verbose_name='statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('soignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='soignant')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'ordering': ['-date', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date du bilan')),
                ('type_examen', models.CharField(blank=True, help_text='Bilan sanguin, imagerie, ECG…', max_length=100, verbose_name="type d'examen")),
                ('compte_rendu', models.TextField(blank=True, verbose_name='compte rendu')),
                ('laboratoire', models.CharField(blank=True, max_length=200, verbose_name='laboratoire')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='dossier.consultation', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'bilan de santé',
                'verbose_name_plural': 'bilans de santé',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre', models.CharField(max_length=120, verbose_name='paramètre')),
                ('valeur', models.CharField(max_length=60, verbose_name='valeur')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='unité')),
                ('norme_min', models.FloatField(blank=True, null=True, verbose_name='norme min')),
                ('norme_max', models.FloatField(blank=True, null=True, verbose_name='norme max')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='référence')),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='dossier.bilan', verbose_name='bilan')),
            ],
            options={
                'verbose_name': 'mesure',
                'verbose_name_plural': 'mesures',
                'ordering': ['parametre'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin'), ('A', 'Autre')], default='F', max_length=1, verbose_name='sexe')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='email')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('numero_dossier', models.CharField(blank=True, max_length=20, unique=True, verbose_name='n° de dossier')),
                ('medecin_traitant', models.CharField(blank=True, max_length=200, verbose_name='médecin traitant')),
                ('notes', models.TextField(blank=True, verbose_name='notes administratives')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='dossier_pat_nom_7f9827_idx')],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='dossier.patient', verbose_name='patient'),
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=200, verbose_name='substance')),
                ('reaction', models.CharField(blank=True, max_length=300, verbose_name='réaction observée')),
                ('gravite', models.CharField(choices=[('legere', 'Légère'), ('moderee', 'Modérée'), ('severe', 'Sévère')], default='legere', max_length=20, verbose_name='gravité')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='dossier.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'allergie',
                'verbose_name_plural': 'allergies',
                'ordering': ['-gravite', 'substance'],
            },
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('echeance', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('fait', models.BooleanField(default=False, verbose_name='fait')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='dossier.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': 'suivi',
                'verbose_name_plural': 'suivis',
                'ordering': ['fait', 'echeance', '-cree_le'],
            },
        ),
    ]
