# Generated by Django 6.1.1 on 2026-09-30 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='horodatage')),
                ('identifiant_utilisateur', models.CharField(blank=True, max_length=150, verbose_name='identifiant (conservé même si le compte est supprimé)')),
                ('role', models.CharField(blank=True, max_length=30, verbose_name="rôle au moment de l'action")),
                ('numero_dossier', models.CharField(blank=True, max_length=20, verbose_name='n° de dossier')),
                ('objet', models.CharField(blank=True, max_length=120, verbose_name='objet concerné')),
                ('action', models.CharField(choices=[('lecture', 'Consultation du dossier'), ('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('refus', 'Accès refusé')], max_length=20, verbose_name='action')),
                ('details', models.CharField(blank=True, max_length=200, verbose_name='détail')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux', to='dossier.patient', verbose_name='patient')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "journal d'accès",
                'verbose_name_plural': "journal d'accès",
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['-horodatage', 'action'], name='dossier_jou_horodat_69b0b5_idx')],
            },
        ),
    ]
