# Generated by Django 6.1.1 on 2026-10-01 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0002_journalacces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_relance', models.CharField(choices=[('soin', 'Relance de soin'), ('vaccin', 'Rappel de vaccin'), ('bilan', 'Bilan à refaire'), ('administratif', 'Rappel administratif')], default='soin', max_length=20, verbose_name='type')),
                ('objet', models.CharField(max_length=200, verbose_name='objet')),
                ('corps', models.TextField(verbose_name='message rédigé')),
                ('motif', models.TextField(blank=True, help_text='Ce qui a déclenché la proposition, en termes factuels', verbose_name='pourquoi cette relance')),
                ('statut', models.CharField(choices=[('brouillon', 'En attente de validation'), ('validee', 'Validée — à envoyer'), ('envoyee', 'Envoyée'), ('abandonnee', 'Abandonnée')], default='brouillon', max_length=20, verbose_name='statut')),
                ('redigee_le', models.DateTimeField(auto_now_add=True, verbose_name='rédigée le')),
                ('validee_le', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('envoyee_le', models.DateTimeField(blank=True, null=True, verbose_name='envoyée le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='dossier.patient', verbose_name='patient')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_validees', to=settings.AUTH_USER_MODEL, verbose_name='validée par')),
            ],
            options={
                'verbose_name': 'relance',
                'verbose_name_plural': 'relances',
                'ordering': ['-redigee_le'],
                'indexes': [models.Index(fields=['statut', '-redigee_le'], name='dossier_rel_statut_748038_idx')],
            },
        ),
    ]
