# Generated by Django 6.1.1 on 2026-10-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0003_relance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom du laboratoire')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('valide_par', models.CharField(blank=True, max_length=150, verbose_name='références validées par')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='validées le')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'laboratoire',
                'verbose_name_plural': 'laboratoires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceIntervalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='code')),
                ('libelle', models.CharField(max_length=200, verbose_name='libellé')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='unité')),
                ('norme_min', models.FloatField(blank=True, null=True, verbose_name='norme basse')),
                ('norme_max', models.FloatField(blank=True, null=True, verbose_name='norme haute')),
                ('sexe', models.CharField(default='', help_text='H, F, M = tous les sexes, vide = tous', max_length=1, verbose_name='sexe')),
                ('age_min', models.IntegerField(blank=True, null=True, verbose_name='âge min (années)')),
                ('age_max', models.IntegerField(blank=True, null=True, verbose_name='âge max (années)')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='en vigueur depuis')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='abrogée le')),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalles', to='dossier.laboratoire', verbose_name='laboratoire')),
            ],
            options={
                'verbose_name': 'fourchette de référence',
                'verbose_name_plural': 'fourchettes de référence',
                'ordering': ['laboratoire', 'libelle'],
                'indexes': [models.Index(fields=['code', 'sexe', 'age_min', 'age_max'], name='dossier_ref_code_4630e3_idx')],
            },
        ),
    ]
